-- SQLite does not allow updating the nullability. Manually updating the schema works

PRAGMA writable_schema = 1;

UPDATE SQLITE_MASTER SET SQL = 'CREATE TABLE "positions" ( "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "mesh_packet_id" integer UNIQUE NOT NULL, "node_id" integer NOT NULL, "latitude_i" integer, "longitude_i" integer, "latitude" real, "longitude" real, "altitude" integer, "time" integer, "location_source" integer, "altitude_source" integer, "timestamp" integer, "altitude_hae" integer, "altitude_geoidal_separation" integer, "pdop" integer, "hdop" integer, "vdop" integer, "gps_accuracy" integer, "ground_speed" integer, "ground_track" integer, "fix_quality" integer, "fix_type" integer, "sats_in_view" integer, "sensor_id" integer, "next_update" integer, "seq_number" integer, "precision_bits" integer, FOREIGN KEY ("mesh_packet_id") REFERENCES "mesh_packets" ("id") ON DELETE CASCADE ) STRICT' WHERE name = 'positions';
UPDATE SQLITE_MASTER SET SQL = 'CREATE TABLE "neighbors" ( "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "mesh_packet_id" integer NOT NULL, "node_id" integer NOT NULL, "neighbor_node_id" integer NOT NULL, "snr" real, "timestamp" integer NOT NULL, FOREIGN KEY ("mesh_packet_id") REFERENCES "mesh_packets" ("id") ON DELETE CASCADE ) STRICT' WHERE name = 'neighbors';
UPDATE SQLITE_MASTER SET SQL = 'CREATE TABLE "device_metrics" ( "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "mesh_packet_id" integer UNIQUE NOT NULL, "node_id" integer NOT NULL, "time" integer, "battery_level" integer, "voltage" real, "channel_utilization" real, "air_util_tx" real, uptime_seconds INTEGER DEFAULT 0, FOREIGN KEY ("mesh_packet_id") REFERENCES "mesh_packets" ("id") ON DELETE CASCADE ) STRICT' WHERE name = 'device_metrics';
UPDATE SQLITE_MASTER SET SQL = 'CREATE TABLE "environment_metrics" ( "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "mesh_packet_id" integer UNIQUE NOT NULL, "node_id" integer NOT NULL, "time" integer, "temperature" real, "relative_humidity" real, "barometric_pressure" real, "gas_resistance" real, iaq INTEGER NOT NULL DEFAULT 0, FOREIGN KEY ("mesh_packet_id") REFERENCES "mesh_packets" ("id") ON DELETE CASCADE ) STRICT' WHERE name = 'environment_metrics';
UPDATE SQLITE_MASTER SET SQL = 'CREATE TABLE "waypoints" ( "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "mesh_packet_id" integer UNIQUE NOT NULL, "node_id" integer NOT NULL, "waypoint_id" integer, "latitude_i" integer, "longitude_i" integer, "latitude" real, "longitude" real, "expire" integer, "locked_to" integer, "name" text, "description" text, "icon" text, FOREIGN KEY ("mesh_packet_id") REFERENCES "mesh_packets" ("id") ON DELETE CASCADE ) STRICT' WHERE name = 'waypoints';

PRAGMA writable_schema = 0;
